// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgyejeoftvdzlvvihdmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhneWVqZW9mdHZkemx2dmloZG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDMwODEsImV4cCI6MjA1OTAxOTA4MX0.BS85jHB_K1KKpF8OWl3CUkVHrlSbtUG3rS_DNg-_SDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);